### ISSUE TITLE
GPU utilization mostly 0% during training

### ISSUE THREAD

**Issue by xuzhang5788** [lmassaron/deep_learning_for_tabular_data#4]
Fri Jan 29 23:29:47 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.38       Driver Version: 455.38       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:01:00.0 Off |                  N/A |
| 32%   32C    P8    23W / 350W |  23081MiB / 24245MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     27737      C   ...rtualenvs/tf24/bin/python    23079MiB |
+-----------------------------------------------------------------------------+

I think my GPU always waits for CPU to process data.  Do you know how to improve the utility of GPU?

**Comment by lmassaron** [comment]
see https://github.com/lmassaron/deep_learning_for_tabular_data/issues/5
